### ISSUE TITLE
Compatibility with the last QGIS versions

### ISSUE THREAD

**Issue by fabiovin** [JuergenWeichand/qgis-complex-gmlinfo-plugin#4]
Hi,

is there any chance that this plugin will be converted for use in the latest versions of QGIS?
It is very useful!

Thanks,
Fabio

**Comment by ejn** [comment]
Hi,

we're working on it!

An initial (beta) version with compatibility for QGIS 3.x is available under https://www.geoportal-mv.de/portal/Geowebdienste/Hinweise_zu_Geowebdiensten (expand "Nutzung von Geowebdiensten in QGIS" and then "Download (ZIP-Archiv, ca. 270 KB)" and install locally in QGIS.

The plan is to push the changes to Github and get the new version into the official QGIS plugin repository soon - but feedback on the beta version is welcome!

Cheers,

Ed

**Comment by fabiovin** [comment]
Hi Ed,
thank you!

I will happy to test it

**Comment by fabiovinci** [comment]
Dear @ejn,

do you happen to have any news about this issue?

**Comment by ejn** [comment]
Hi @fabiovinci - this issue should really be closed. The plugin has been available for QGIS 3 since April 2020: https://plugins.qgis.org/plugins/ComplexGmlInfo/

As it may cause performance problems with large GML objects then it is still marked as experimental - so you will have to enable experimental plugins in QGIS plugin manager to see it (or download and install directly.

Please let me know if you have problems, otherwise I will close this ticket as completed.

**Comment by fabiovinci** [comment]
Hi @ejn,

thank you for getting back to me so quickly.

I installed it but I received the following Python error:

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "C:\Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ComplexGmlInfo\gmlinfo.py", line 206, in run
    self.displayFeatureInfo()
  File "C:\Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ComplexGmlInfo\gmlinfo.py", line 241, in displayFeatureInfo
    tool = SelectTool(self.iface, self.show_Info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ComplexGmlInfo\selectTool.py", line 12, in __init__
    self.rubberBand = QgsRubberBand(self.canvas, True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'


Versione Python: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.38.3-Grenoble Grenoble, 37f9e6efee 

Percorso Python:
C:\Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\merge_selected_features
C:\Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mappia_publisher
C:/OSGeo4W/apps/qgis/./python
C:/Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\Users\fabio\OneDrive\Documenti
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python

Have you any idea?

**Comment by ejn** [comment]
I tested it with the newest version I've got here (unfortunately now rather old) and didn't have this problem. I can't find whether there has been an API change in QGIS (I don't think so), but this could be a problem with a newer version of Python and a bad argument.

Would it be possible for you to manually edit the contents of the file C:\Users\fabio\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ComplexGmlInfo\selectTool.py and in line 12 delete the `True` argument, so that it looks like this:
```python
self.rubberBand = QgsRubberBand(self.canvas)
```

You would then need to restart QGIS before testing.

If that works then I would fix up the code and release a new plugin version.

**Comment by fabiovinci** [comment]
Great! It works now!

**Comment by ejn** [comment]
Excellent - I will try to get a bugfix uploaded to the plugin repo soon: It will take a little time as I don't have a development enviroment set up currently, but I hope to find time over the festive season.

**Comment by ejn** [comment]
Should be fixed with the new 0.6 release version

**Comment by fabiovinci** [comment]
Dear @ejn,

many thank for the update.

I couldn't find it in the Plug-in manager, so I installed it from the zip file, and it works.
Is it possible to have it in the Plug-in manager?

<img width="1289" height="735" alt="Image" src="https://github.com/user-attachments/assets/09e31068-54f9-4666-aa2f-50fecb8869d0" />

**Comment by ejn** [comment]
I'm currently experiencing technical problems uploading it to the official QGIS Plugin Repo, but once that's done and it's approved then it will appear in the plugin manager.
